#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_EYEFISERVER_XPATH="/config/services/eyefiserver"
OMV_EYEFISERVER_CONF="/etc/eyefiserver.conf"

cat <<EOF > ${OMV_EYEFISERVER_CONF}
[EyeFiServer]

# host name and port to listen on
# you can leave hostname empty for localhost

host_name:
host_port:59278

# To use this script you need to have your Eye-Fi upload key.
# You can find it after configuring the card,
# which you can currently on do on windows or mac
# It is inside C:\Documents and Settings\<User>\Application Data\Eye-Fi\Settings.xml on windows
# or ~/Applications Data/Eye-Fi/Settings.xml on mac
# search for it and paste it here:

#enable           $(omv_config_get "${OMV_EYEFISERVER_XPATH}/enable")
mac_0:$(omv_config_get "${OMV_EYEFISERVER_XPATH}/card_mac_address")
upload_key_0:$(omv_config_get "${OMV_EYEFISERVER_XPATH}/upload_key")

# Create XMP file with geolocation information based on access points
# detected by Eye-Fi card for any uploaded JPEG or RAW file
geotag_enable:1

# Use acces points detected within this period of time
# before or after photo was taken, in seconds
geotag_lag:3600

# Use acquired geolocation data with accuracy over this value, in meters
geotag_accuracy:140000

# When connecting, all files are downloaded in one directory
# the name of the directory can be a strftime formatted string like
# /home/myblog/pictures/%%Y-%%m-%%d
# notice the double percent sign to escape % from ini interpolation
upload_dir:$(xmlstarlet sel -t -m ${OMV_EYEFISERVER_XPATH} ${OMV_XMLSTARLET_GET_SHAREDFOLDER_PATH} ${OMV_CONFIG_FILE})$(omv_config_get "${OMV_EYEFISERVER_XPATH}/sub_directory_schema")

# The UID of the user that you want to own the uploaded images (if commented out, ownership of files will not be changed)
upload_uid:$(id -u $(omv_config_get "${OMV_EYEFISERVER_XPATH}/upload_user"))
# The GID of the group that you want to own the uploaded images (if commented out, group of files will not be changed)
upload_gid:$(id -g $(omv_config_get "${OMV_EYEFISERVER_XPATH}/upload_group"))
# The permissions to use for the uploaded images
upload_file_mode:420
# The permissions to use for the directories that are created
upload_dir_mode:509

EOF

exit 0
